---
kind: Service
apiVersion: v1
metadata:
  name: nginx
  namespace: default
  labels:
    tier: webserver
    environment: staging
spec:
  selector:
    tier: webserver
    environment: staging
  ports:
  - protocol: TCP
    port: 80
    name: http
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx
  namespace: default
  labels:
    tier: webserver
    environment: staging
spec:
  replicas: 3
  template:
    metadata:
      labels:
        tier: webserver
        environment: staging
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - name: http
              containerPort: 80
