---
kind: Service
apiVersion: v1
metadata:
  name: nginx
  namespace: default
  labels:
    tier: webserver
    environment: staging
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "<ACM-ARN>" 
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
spec:
  selector:
    tier: webserver
    environment: staging
  ports:
  - protocol: TCP
    port: 443
    name: https
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx
  namespace: default
  labels:
    tier: webserver
    environment: staging
spec:
  replicas: 3
  template:
    metadata:
      labels:
        tier: webserver
        environment: staging
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - name: http
              containerPort: 80